//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_Chap7.ProductsInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/TP_Chap7_WCF")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TP_Chap7.ProductsInfo.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TP_Chap7.ProductsInfo.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((this.CategoryField.Equals(value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/TP_Chap7_WCF")]
    public enum Category : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Clothes = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fruits = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vegetables = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shoes = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductsInfo.IProductsInfo")]
    public interface IProductsInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsInfo/GetProductsInformation", ReplyAction="http://tempuri.org/IProductsInfo/GetProductsInformationResponse")]
        System.Collections.Generic.List<TP_Chap7.ProductsInfo.ProductDTO> GetProductsInformation(string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductsInfo/GetProductsInformation", ReplyAction="http://tempuri.org/IProductsInfo/GetProductsInformationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<TP_Chap7.ProductsInfo.ProductDTO>> GetProductsInformationAsync(string search);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductsInfoChannel : TP_Chap7.ProductsInfo.IProductsInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductsInfoClient : System.ServiceModel.ClientBase<TP_Chap7.ProductsInfo.IProductsInfo>, TP_Chap7.ProductsInfo.IProductsInfo {
        
        public ProductsInfoClient() {
        }
        
        public ProductsInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductsInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductsInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<TP_Chap7.ProductsInfo.ProductDTO> GetProductsInformation(string search) {
            return base.Channel.GetProductsInformation(search);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<TP_Chap7.ProductsInfo.ProductDTO>> GetProductsInformationAsync(string search) {
            return base.Channel.GetProductsInformationAsync(search);
        }
    }
}
